spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:h2:mem:employee-db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    connectionTimeout: 30000
    maxLifeTime: 600000
    maximumPoolSize: 5
    idleTimeout: 30000
    minimumIdle: 1
    leakDetectionThreshold: 20000
    connectionTestQuery: SELECT 1
    readOnly: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /api/v1

management:
  prometheus:
    metrics:
      export:
        properties:
          io:
            prometheus:
              exporter:
                exemplarsOnAllMetricTypes: false
  tracing:
    sampling:
      probability: 1.0

  server:
    port: 10103
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "health,prometheus,info,db,metrics"
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      probes:
        enabled: true

mandatory:
  headers:
    routesToSkip:
      - "/api/actuator"
    startsWith:
      - "/api/actuator/"
