spring:
  application:
    name: employee-service

  datasource:
    url: ${DB_HOST_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    connectionTimeout: 60000
    maxLifeTime: 90000
    maximumPoolSize: 20
    idleTimeout: 90000
    minimumIdle: 10
    leakDetectionThreshold: 30000
    connectionTestQuery: SELECT 1
    readOnly: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO

management:
  prometheus:
    metrics:
      export:
        properties:
          io:
            prometheus:
              exporter:
                exemplarsOnAllMetricTypes: false
  tracing:
    sampling:
      probability: 1.0

  server:
    port: 10103
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "health,prometheus,info,db,metrics"
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      probes:
        enabled: true

mandatory:
  headers:
    routesToSkip:
      - "/api/actuator"
    startsWith:
      - "/api/actuator/"

application:
  employee-management:
    seed: true

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'